import pandas as pd
from datetime import datetime
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from pathlib import Path


REPORT_DIR = Path("reports")
REPORT_DIR.mkdir(exist_ok=True)


def safe_sum(df, col):
    if df is None or df.empty:
        return 0
    if col not in df.columns:
        return 0
    return pd.to_numeric(df[col], errors="coerce").fillna(0).sum()


def generate_daily_report_pdf(sales_df, cash_summary, cashier="System"):

    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)

    y = 750
    date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    file_date = datetime.now().strftime("%Y%m%d_%H%M%S")

    # =========================
    # HEADER
    # =========================
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(150, y, "AZIEL INVESTMENTS - DAILY REPORT")
    y -= 25

    pdf.setFont("Helvetica", 10)
    pdf.drawString(50, y, f"Date: {date}")
    y -= 20

    # =========================
    # SAFETY FIX
    # =========================
    if sales_df is None:
        sales_df = pd.DataFrame()

    for col in ["total", "profit", "items", "name"]:
        if col not in sales_df.columns:
            sales_df[col] = 0

    total_sales = safe_sum(sales_df, "total")
    total_profit = safe_sum(sales_df, "profit")
    total_items = safe_sum(sales_df, "items")

    # =========================
    # SALES SUMMARY
    # =========================
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, y, "SALES SUMMARY")
    y -= 20

    pdf.setFont("Helvetica", 10)
    pdf.drawString(50, y, f"Revenue: ${total_sales:.2f}")
    y -= 15

    pdf.drawString(50, y, f"Profit: ${total_profit:.2f}")
    y -= 15

    pdf.drawString(50, y, f"Items Sold: {int(total_items)}")
    y -= 25

    # =========================
    # CASH SUMMARY
    # =========================
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, y, "CASH SUMMARY")
    y -= 20

    for key, value in cash_summary.items():
        pdf.setFont("Helvetica", 10)
        pdf.drawString(50, y, f"{key}: ${float(value):.2f}")
        y -= 15

    # =========================
    # TOP PRODUCTS
    # =========================
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, y, "TOP PRODUCTS")
    y -= 20

    if "name" in sales_df.columns:
        top = sales_df.groupby("name")["items"].sum().sort_values(ascending=False).head(5)

        for name, qty in top.items():
            pdf.drawString(50, y, f"{name} - {qty}")
            y -= 15

    # =========================
    # FOOTER
    # =========================
    pdf.setFont("Helvetica-Oblique", 9)
    pdf.drawString(50, 50, f"Generated by: {cashier}")

    pdf.save()
    buffer.seek(0)

    pdf_bytes = buffer.getvalue()

    # =========================
    # SAVE COPY FOR LATER ANALYSIS
    # =========================
    file_path = REPORT_DIR / f"daily_report_{file_date}.pdf"

    with open(file_path, "wb") as f:
        f.write(pdf_bytes)

    return pdf_bytes