import pandas as pd
from datetime import datetime
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from pathlib import Path

import streamlit as st

from backend.core.db_adapter import load_branches


REPORT_DIR = Path("reports")
REPORT_DIR.mkdir(exist_ok=True)


# ==============================
# SESSION BRANCH HELPERS
# ==============================
def _get_session_branch():
    """
    Return the authoritative branch for the current session.
    Prefers `current_branch_code` (set by the branch-selection screen)
    over `user_branch` (which may be a stale default).
    """
    return (
        st.session_state.get("current_branch_code")
        or st.session_state.get("user_branch")
        or "HO"
    )


def _branch_slug(branch_id):
    """Filesystem-safe branch code."""
    if not branch_id:
        return "HO"
    return str(branch_id).strip().upper().replace(" ", "_")


def _branch_label(branch_id):
    """Human-readable branch label: 'Name (CODE)' when available."""
    if not branch_id:
        return "HO"
    try:
        df = load_branches()
        if df is not None and not df.empty and "branch_id" in df.columns:
            match = df[df["branch_id"].astype(str).str.upper() == str(branch_id).upper()]
            if not match.empty:
                name = match.iloc[0].get("branch_name", "")
                if name:
                    return f"{name} ({branch_id})"
    except Exception:
        pass
    return str(branch_id)


# ==============================
# SAFE SUM
# ==============================
def safe_sum(df, col):
    if df is None or df.empty:
        return 0
    if col not in df.columns:
        return 0
    return pd.to_numeric(df[col], errors="coerce").fillna(0).sum()


# ==============================
# DAILY REPORT PDF (branch-scoped)
# ==============================
def generate_daily_report_pdf(
    sales_df,
    cash_summary,
    cashier="System",
    branch_id=None,
    branch_label=None,
):
    """
    Generate a daily report PDF.

    Branch-safety:
      - `branch_id` defaults to the session branch.
      - `branch_label` defaults to 'Name (CODE)' from the branches table.
      - The PDF is written to `reports/{branch_id}/daily_report_{file_date}.pdf`
        so different branches never overwrite each other's files.
      - The header shows the branch label.
    """
    if branch_id is None:
        branch_id = _get_session_branch()
    if branch_label is None:
        branch_label = _branch_label(branch_id)

    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)

    y = 750
    date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    file_date = datetime.now().strftime("%Y%m%d_%H%M%S")

    # =========================
    # HEADER
    # =========================
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(150, y, "AZIEL INVESTMENTS - DAILY REPORT")
    y -= 18

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(150, y, f"Branch: {branch_label}")
    y -= 22

    pdf.setFont("Helvetica", 10)
    pdf.drawString(50, y, f"Date: {date}")
    y -= 20

    # =========================
    # SAFETY FIX
    # =========================
    if sales_df is None:
        sales_df = pd.DataFrame()

    for col in ["total", "profit", "items", "name"]:
        if col not in sales_df.columns:
            sales_df[col] = 0

    total_sales = safe_sum(sales_df, "total")
    total_profit = safe_sum(sales_df, "profit")
    total_items = safe_sum(sales_df, "items")

    # =========================
    # SALES SUMMARY
    # =========================
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, y, "SALES SUMMARY")
    y -= 20

    pdf.setFont("Helvetica", 10)
    pdf.drawString(50, y, f"Revenue: ${total_sales:.2f}")
    y -= 15

    pdf.drawString(50, y, f"Profit: ${total_profit:.2f}")
    y -= 15

    pdf.drawString(50, y, f"Items Sold: {int(total_items)}")
    y -= 25

    # =========================
    # CASH SUMMARY
    # =========================
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, y, "CASH SUMMARY")
    y -= 20

    for key, value in cash_summary.items():
        pdf.setFont("Helvetica", 10)
        pdf.drawString(50, y, f"{key}: ${float(value):.2f}")
        y -= 15

    # =========================
    # TOP PRODUCTS
    # =========================
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, y, "TOP PRODUCTS")
    y -= 20

    if "name" in sales_df.columns:
        top = sales_df.groupby("name")["items"].sum().sort_values(ascending=False).head(5)

        for name, qty in top.items():
            pdf.drawString(50, y, f"{name} - {qty}")
            y -= 15

    # =========================
    # FOOTER
    # =========================
    pdf.setFont("Helvetica-Oblique", 9)
    pdf.drawString(50, 50, f"Generated by: {cashier}")
    pdf.drawString(50, 38, f"Branch: {branch_label}")

    pdf.save()
    buffer.seek(0)

    pdf_bytes = buffer.getvalue()

    # =========================
    # SAVE COPY FOR LATER ANALYSIS (branch-scoped folder)
    # =========================
    branch_dir = REPORT_DIR / _branch_slug(branch_id)
    branch_dir.mkdir(parents=True, exist_ok=True)
    file_path = branch_dir / f"daily_report_{file_date}.pdf"

    with open(file_path, "wb") as f:
        f.write(pdf_bytes)

    return pdf_bytes